TEAM_TO_TEAM_ABBR = {
        'ATLANTA HAWKS': 'ATL',
        'ST. LOUIS HAWKS': 'SLH',
        'MILWAUKEE HAWKS': 'MIL',
        'TRI-CITIES BLACKHAWKS': 'TCB',
        'BOSTON CELTICS': 'BOS',
        'BROOKLYN NETS': 'BRK',
        'NEW JERSEY NETS' : 'NJN',
        'NEW YORK NETS' : 'NYN',
        'CHICAGO BULLS': 'CHI',
        'CHARLOTTE HORNETS': 'CHO',
        'CHARLOTTE BOBCATS' : 'CHA',
        'CLEVELAND CAVALIERS': 'CLE',
        'DALLAS MAVERICKS': 'DAL',
        'DENVER NUGGETS': 'DEN',
        'DETROIT PISTONS': 'DET',
        'FORT WAYNE PISTONS': 'FWP',
        'GOLDEN STATE WARRIORS': 'GSW',
        'SAN FRANCISCO WARRIORS': 'SFW',
        'PHILADELPHIA WARRIORS': 'PHI',
        'HOUSTON ROCKETS': 'HOU',
        'SAN DIEGO ROCKETS': 'HOU',
        'INDIANA PACERS': 'IND',
        'LOS ANGELES CLIPPERS': 'LAC',
        'SAN DIEGO CLIPPERS': 'SDC',
        'BUFFALO BRAVES': 'BUF',
        'LOS ANGELES LAKERS': 'LAL',
        'MINNEAPOLIS LAKERS': 'MIN',
        'MEMPHIS GRIZZLIES': 'MEM',
        'VANCOUVER GRIZZLIES' : 'VAN',
        'MIAMI HEAT': 'MIA',
        'MILWAUKEE BUCKS': 'MIL',
        'MINNESOTA TIMBERWOLVES': 'MIN',
        'NEW ORLEANS PELICANS' : 'NOP',
        'NEW ORLEANS/OKLAHOMA CITY HORNETS' : 'NOK',
        'NEW ORLEANS HORNETS' : 'NOH',
        'NEW YORK KNICKS' : 'NYK',
        'OKLAHOMA CITY THUNDER' : 'OKC',
        'SEATTLE SUPERSONICS' : 'SEA',
        'ORLANDO MAGIC' : 'ORL',
        'PHILADELPHIA 76ERS' : 'PHI',
        'SYRACUSE NATIONALS' : 'SYR',
        'PHOENIX SUNS' : 'PHO',
        'PORTLAND TRAIL BLAZERS' : 'POR',
        'SACRAMENTO KINGS' : 'SAC',
        'KANSAS CITY KINGS' : 'KCK',
        'KANSAS CITY-OMAHA KINGS' : 'KCK',
        'CINCINNATI ROYALS' : 'CIN',
        'ROCHESTER ROYALS': 'ROR',
        'SAN ANTONIO SPURS' : 'SAS',
        'TORONTO RAPTORS' : 'TOR',
        'UTAH JAZZ' : 'UTA',
        'NEW ORLEANS JAZZ' : 'NOJ',
        'WASHINGTON WIZARDS' : 'WAS',
        'WASHINGTON BULLETS' : 'WAS',
        'CAPITAL BULLETS' : 'CAP',
        'BALTIMORE BULLETS' : 'BAL',
        'CHICAGO ZEPHYRS' : 'CHI',
        'CHICAGO PACKERS' : 'CHI',

        # DEFUNCT FRANCHISES
        'ANDERSON PACKERS': 'AND',
        'CHICAGO STAGS': 'CHI',
        'INDIANAPOLIS OLYMPIANS': 'IND',
        'SHEBOYGAN RED SKINS': 'SRS',
        'ST. LOUIS BOMBERS': 'SLB',
        'WASHINGTON CAPITOLS' : 'WAS',
        'WATERLOO HAWKS': 'WAT',
        }
TEAM_SETS = [['STL', 'TRI', 'MLH', 'ATL'],
 ['BOS'],
 ['NJN', 'BRK', 'NYN', 'NJA', 'NYA'],
 ['CHO', 'CHA', 'CHH'],
 ['CHI'],
 ['CLE'],
 ['DAL'],
 ['DEN', 'DNR', 'DNA'],
 ['DET', 'FTW'],
 ['GSW', 'SFW', 'PHW'],
 ['SDR', 'HOU'],
 ['INA', 'IND'],
 ['SDC', 'LAC', 'BUF'],
 ['LAL', 'MNL'],
 ['MEM', 'VAN'],
 ['MIA'],
 ['MIL'],
 ['MIN'],
 ['NOP', 'NOH', 'NOK'],
 ['NYK'],
 ['SEA', 'OKC'],
 ['ORL'],
 ['PHI', 'SYR'],
 ['PHO'],
 ['POR'],
 ['CIN', 'SAC', 'KCO', 'KCK', 'ROC'],
 ['DLC', 'SAA', 'SAS', 'TEX'],
 ['TOR'],
 ['NOJ', 'UTA'],
 ['WSB', 'CHP', 'CAP', 'BAL', 'WAS', 'CHZ']]


def get_team_set(team_code):
    for team_set in TEAM_SETS:
        if team_code in team_set:
            return team_set
    return None


CATEGORY_COLUMNS = {
        'per_game': ['SEASON', 'AGE', 'TEAM', 'LEAGUE', 'POS', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS'],
        'totals': ['2P', '2P%', '2PA', '3P', '3P%', '3PA', 'AGE', 'AST', 'BLK', 'DRB', 'FG', 'FG%', 'FGA', 'FT', 'FT%', 'FTA', 'G', 'GS', 'LEAGUE', 'MP', 'ORB', 'PF', 'POS', 'PTS', 'SEASON', 'STL', 'TEAM', 'TOV', 'TRB', 'eFG%'],
        'per_minute': ['SEASON', 'AGE', 'TEAM', 'LEAGUE', 'POS', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS'],
        'per_poss': ['SEASON', 'AGE', 'TEAM', 'LEAGUE', 'POS', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'ORtg', 'DRtg'],
        'advanced': ['SEASON', 'AGE', 'TEAM', 'LEAGUE', 'POS', 'G', 'MP', 'PER', 'TS%', '3PAr', 'FTr', 'ORB%', 'DRB%', 'TRB%', 'AST%', 'STL%', 'BLK%', 'TOV%', 'USG%', 'OWS', 'DWS', 'WS', 'WS/48', 'OBPM', 'DBPM', 'BPM', 'VORP'],
        'adj_shooting': ['SEASON', 'AGE', 'TEAM', 'LEAGUE', 'POS', 'G', 'MP', 'FG', '2P', '3P', 'eFG%', 'FT', 'TS', 'FTr', '3PAr', 'FG', '2P', '3P', 'eFG%', 'FT', 'TS', 'FTr', '3PAr', 'FG+', '2P+', '3P+', 'eFG+', 'FT+', 'TS+', 'FTr+', '3PAr+', 'FG Add', 'TS Add'],
        'shooting': ['# Dunks', '# Heaves', '% of FGA 0-3', '% of FGA 10-16', '% of FGA 16-3P', '% of FGA 2P', '% of FGA 3-10', '% of FGA 3P', '%3PA Corner 3s', '%FGA Dunks', '0-3 FG%', '10-16 FG%', '16-3P FG%', '2P % AST', '2P FG%', '3-10 FG%', '3P % AST', '3P FG%', '3P% Corner 3s', 'AGE', 'Att. Heaves', 'Dist.', 'FG%', 'G', 'LEAGUE', 'MP', 'POS', 'SEASON', 'TEAM']

}

CATEGORIES = ["per_game", "totals", "per_minute", "per_poss", "advanced", "adj_shooting", "shooting"]
TEAM_CATEGORIES = ['totals','per_game','per_poss','shooting','advanced']